jtype: Flow
version: '1'
with:
  protocol: 'http'
  cors: True
  port_expose: '45678'
executors:
  - name: encoder
    uses: jinahub://DPRTextEncoder/v0.2
    uses_with:
      encoder_type: 'question'
      batch_size: 1
  - name: vec_indexer
    uses: jinahub://FaissPostgresIndexer/v0.3
    uses_with:
      total_shards: 1
      hostname: '127.0.0.1'
      port: 5432
      username: 'postgres'
      password: '123456'
      database: 'postgres'
      table: 'kv_indexer'
  - name: match_extender  # expand the matches with sliding windows
    uses: MatchExtender
    uses_with:
      window_size: 4
    py_module:
      - executors.py
  - name: kv_indexer
    uses: jinahub://PostgreSQLStorage/v0.1
    uses_with:
      hostname: '127.0.0.1'
      port: 5432
      username: 'postgres'
      password: '123456'
      database: 'postgres'
      table: 'kv_indexer'
      return_embeddings: False
      default_traversal_paths:
        - 'm'
  - name: ranker
    uses: DPRReaderRanker  # extract the answers from the matches, save the location information
    py_module:
      - executors.py
    uses_with:
      num_spans_per_match: 1
  - name: text2frame_converter  # calculate the location based on the text
    uses: Text2Frame
    py_module:
      - executors.py